version: "3"
virtualmachines:
- name: proxy-host
  image: centos-cloud/centos-7
  shell: /bin/bash
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: isolated-host
  image: kots-field-labs/instruqt-airgap
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
