version: "3"
virtualmachines:
  - name: jumpstation
    image: ubuntu-os-cloud/ubuntu-2004-lts
    shell: /bin/bash
    machine_type: n1-standard-4
    allow_external_ingress:
    - http
    - https
    - high-ports
  - name: airgap
    image: ubuntu-os-cloud/ubuntu-2004-lts
    shell: /bin/bash
    machine_type: n1-standard-4
  - name: cli
    image: ubuntu-os-cloud/ubuntu-2004-lts
    shell: /bin/bash
    machine_type: n1-standard-1
  - name: init
    image: ubuntu-os-cloud/ubuntu-2004-lts
    shell: /bin/bash
    machine_type: n1-standard-1