version: "3"
containers:
  - name: cli
    image: ubuntu
    shell: /bin/bash
    memory: 256
  - name: jumpstation
    image: gcr.io/instruqt/cloud-client
    ports: [80]
    shell: /bin/bash
gcp_projects:
- name: gcpproject
  services: [compute.googleapis.com]